In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python

#Imports
import glob
import functools
import datetime as dt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
import re
import numpy as np 
import pandas as pd

# Input data files are available in the read-only "../input/" directory

import os

In [ ]:
for dirname, _, filenames in os.walk('D:\AILA 2019\Object_casedocs'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

NameError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import glob
import csv

read_files = glob.glob('D:\AILA 2019\Object_casedocs\*')

with open("object_casedocs.csv", "w") as outfile:
    w=csv.writer(outfile)
    for f in read_files:
        with open(f, "r") as infile:
            w.writerow([" ".join([line.strip() for line in infile])])

lst_arr = os.listdir("D:\AILA 2019\Object_casedocs")
df_filename = pd.DataFrame(lst_arr, columns = ['Name'])
df_filename

           Name
0        C1.txt
1       C10.txt
2      C100.txt
3     C1000.txt
4     C1001.txt
...         ...
2909   C995.txt
2910   C996.txt
2911   C997.txt
2912   C998.txt
2913   C999.txt

[2914 rows x 1 columns]

In [ ]:
evaluate = pd.read_csv(r'D:\AILA 2019\relevance_judgments_priorcases.txt', delimiter = " ", header = None)
evaluate.columns = ["Query_Number", "Q0", "Document" ,"Relevance"]
evaluate=evaluate.drop(columns=["Q0"])
evaluate

       Query_Number Document  Relevance
0           AILA_Q1     C168          0
1           AILA_Q1     C382          0
2           AILA_Q1     C428          0
3           AILA_Q1     C949          0
4           AILA_Q1    C2303          0
...             ...      ...        ...
145695     AILA_Q50    C1367          0
145696     AILA_Q50    C2079          0
145697     AILA_Q50    C2066          0
145698     AILA_Q50    C1951          0
145699     AILA_Q50    C1111          0

[145700 rows x 3 columns]

In [ ]:
df = pd.read_csv('object_casedocs.csv',header=None)
df.columns = ["Text"]
df

                                                   Text
0     Masud Khan v State Of Uttar Pradesh Supreme Co...
1     Prabhakaran Nair, Etc. v State Of Tamil Nadu A...
2     Hiten P. Dalal v Bratindranath Banerjee Suprem...
3     Ashok Kumar and Others v State of Tamil Nadu S...
4     Ashok Dhingra v N.C.T. of Delhi Supreme Court ...
...                                                 ...
2909  Rajendra Singh v State of Uttaranchal Supreme ...
2910  Food Corporation Of India & Anr v Seil Ltd. & ...
2911  State of Kerala v Sasi Supreme Court of India ...
2912  Columbia Sportswear Company v Director Of Inco...
2913  Bharat Gurjar and others v State of Rajasthan ...

[2914 rows x 1 columns]

In [ ]:
df = pd.concat([df_filename,df], axis = 1)
df

           Name                                               Text
0        C1.txt  Masud Khan v State Of Uttar Pradesh Supreme Co...
1       C10.txt  Prabhakaran Nair, Etc. v State Of Tamil Nadu A...
2      C100.txt  Hiten P. Dalal v Bratindranath Banerjee Suprem...
3     C1000.txt  Ashok Kumar and Others v State of Tamil Nadu S...
4     C1001.txt  Ashok Dhingra v N.C.T. of Delhi Supreme Court ...
...         ...                                                ...
2909   C995.txt  Rajendra Singh v State of Uttaranchal Supreme ...
2910   C996.txt  Food Corporation Of India & Anr v Seil Ltd. & ...
2911   C997.txt  State of Kerala v Sasi Supreme Court of India ...
2912   C998.txt  Columbia Sportswear Company v Director Of Inco...
2913   C999.txt  Bharat Gurjar and others v State of Rajasthan ...

[2914 rows x 2 columns]

In [ ]:
len(df)

2914

In [ ]:
df.shape

(2914, 2)

In [ ]:
df.info

<bound method DataFrame.info of            Name                                               Text
0        C1.txt  Masud Khan v State Of Uttar Pradesh Supreme Co...
1       C10.txt  Prabhakaran Nair, Etc. v State Of Tamil Nadu A...
2      C100.txt  Hiten P. Dalal v Bratindranath Banerjee Suprem...
3     C1000.txt  Ashok Kumar and Others v State of Tamil Nadu S...
4     C1001.txt  Ashok Dhingra v N.C.T. of Delhi Supreme Court ...
...         ...                                                ...
2909   C995.txt  Rajendra Singh v State of Uttaranchal Supreme ...
2910   C996.txt  Food Corporation Of India & Anr v Seil Ltd. & ...
2911   C997.txt  State of Kerala v Sasi Supreme Court of India ...
2912   C998.txt  Columbia Sportswear Company v Director Of Inco...
2913   C999.txt  Bharat Gurjar and others v State of Rajasthan ...

[2914 rows x 2 columns]>

In [ ]:
import re
#Convert lowercase remove punctuation and Character and then strip 
text = df.iloc[0]
print(text)
text = re.sub(r'[^\w\s]', '', str(text).lower().strip())
txt = text.split()
print(txt)

Name                                               C1.txt
Text    Masud Khan v State Of Uttar Pradesh Supreme Co...
Name: 0, dtype: object
['name', 'c1txt', 'text', 'masud', 'khan', 'v', 'state', 'of', 'uttar', 'pradesh', 'supreme', 'co', 'name', '0', 'dtype', 'object']

In [ ]:
#remove stopwords
import nltk
lst_stopwords = nltk.corpus.stopwords.words("english")
txt = [word for word in txt if word not in lst_stopwords]
print(txt)

['name', 'c1txt', 'text', 'masud', 'khan', 'v', 'state', 'uttar', 'pradesh', 'supreme', 'co', 'name', '0', 'dtype', 'object']

In [ ]:
ps = nltk.stem.porter.PorterStemmer()
print([ps.stem(word) for word in txt])

['name', 'c1txt', 'text', 'masud', 'khan', 'v', 'state', 'uttar', 'pradesh', 'suprem', 'co', 'name', '0', 'dtype', 'object']

In [ ]:
nltk.download('wordnet')
lem = nltk.stem.wordnet.WordNetLemmatizer()
print([lem.lemmatize(word) for word in txt])

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\punee\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

['name', 'c1txt', 'text', 'masud', 'khan', 'v', 'state', 'uttar', 'pradesh', 'supreme', 'co', 'name', '0', 'dtype', 'object']

In [ ]:
#to apply all the technique to all the records on dataset
def utils_preprocess_text(text, flg_stemm=True, flg_lemm =True, lst_stopwords=None ):
    text = re.sub(r'[^\w\s]', '', str(text).lower().strip())
    
    #tokenization(convert from string to List)
    lst_text = text.split()
    
    #remove stopwords
    if lst_stopwords is not None:
        lst_text = [word for word in lst_text if word not in
                   lst_stopwords]
        
     #stemming
    if flg_stemm == True:
        ps = nltk.stem.porter.PorterStemmer()
        lst_text = [ps.stem(word) for word in lst_text]
        
    #Lemmentization
    if flg_lemm == True:
        lem = nltk.stem.wordnet.WordNetLemmatizer()
        lst_text = [lem.lemmatize(word) for word in lst_text]
        
    # back to string from list
    text = " ".join(lst_text)
    return text

df['clean_text'] = df['Text'].apply(lambda x: utils_preprocess_text(x, flg_stemm = False, flg_lemm=True))

In [ ]:
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)

In [ ]:
corpus_array_processed=np.load('/content/drive/MyDrive/corpus.npy').tolist()

In [ ]:
sen = corpus_array_processed
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')
#Encoding:
sen_embeddings = model.encode(sen)
sen_embeddings.shape

(2914, 768)

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.20.1-py3-none-any.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 14.9 MB/s
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Downloading tokenizers-0.12.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
     |████████████████████████████████| 6.6 MB 65.9 MB/s
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.64.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.7.1)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 73.0 MB/s
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.12.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers) (21.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.21.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2022.6.2)
Collecting huggingface-hub<1.0,>=0.1.0
  Downloading huggingface_hub-0.8.1-py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 12.8 MB/s
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.8.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Installing collected packages: pyyaml, tokenizers, huggingface-hub, transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed huggingface-hub-0.8.1 pyyaml-6.0 tokenizers-0.12.1 transformers-4.20.1

In [ ]:
from transformers import AutoTokenizer, AutoModel

In [ ]:
print(set(corpus_array_processed[0]))

{'7', ',', 'W', 'k', 'd', 'Z', '5', 'l', 'F', 'O', ' ', 'P', 'R', '6', '0', 'f', 'I', 's', 'm', 'A', 'z', 'w', ':', 'u', 'C', 'N', 'y', ';', 'L', 'x', 'K', '.', 'v', 'B', 't', ')', 'G', "'", '2', 'T', 'g', 'j', 'p', 'i', '8', 'a', '-', 'Q', 'h', 'o', '(', 'e', 'M', 'S', '3', '4', 'U', 'J', 'q', 'c', '9', 'H', 'n', 'E', 'D', '1', 'b', '"', 'r'}

In [ ]:
z=[]
sen = corpus_array_processed
model = AutoModel.from_pretrained("nlpaueb/legal-bert-small-uncased")
tokenizer = AutoTokenizer.from_pretrained("nlpaueb/legal-bert-small-uncased")
#Encoding:

encoded_input = tokenizer(sen[0:100], return_tensors='pt',padding=True,truncation=True)
outputs = model(**encoded_input)
outputs_np = np.array(outputs[1].detach().numpy())

Some weights of the model checkpoint at nlpaueb/legal-bert-small-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [ ]:
print(z[:10])

[array([[ 4.39276956e-02,  3.59249227e-02,  9.36881125e-01,
        -3.00024301e-01,  1.62629545e-01, -5.23521751e-02,
        -3.73268187e-01, -5.16438484e-02,  8.58702779e-01,
        -1.15892999e-01,  8.68234575e-01,  3.11844528e-01,
         6.18993461e-01, -9.29912210e-01, -6.50453985e-01,
         3.53374094e-01,  2.94812888e-01, -2.92269975e-01,
        -3.63954395e-01,  3.14869940e-01,  1.60980180e-01,
        -3.76389474e-01,  8.49011302e-01, -3.34568508e-02,
         4.66625929e-01, -7.21312225e-01,  2.68785894e-01,
         8.06639910e-01,  6.49580285e-02, -5.56055725e-01,
        -7.85498470e-02,  5.16551614e-01,  3.68784666e-01,
        -6.37445673e-02,  9.27398026e-01, -5.99787891e-01,
         4.61569160e-01, -1.41003542e-02,  6.38104901e-02,
        -2.07872361e-01, -5.18989637e-02,  1.71517149e-01,
        -6.85104191e-01, -9.19773698e-01,  8.65065679e-02,
        -1.60662755e-01,  9.80023146e-01,  2.36807674e-01,
         1.43141627e-01, -9.48965847e-01, -9.42125916e-01,
        -9.26978648e-01, -5.31713665e-01, -1.11662820e-01,
        -7.07289129e-02,  6.37133300e-01,  4.30277020e-01,
         4.51126784e-01, -2.21293330e-01,  1.08232044e-01,
        -9.80815664e-02,  4.90610033e-01,  5.76090753e-01,
        -4.95818228e-01, -9.95975137e-01, -9.62745786e-01,
         2.32369170e-01,  2.45712847e-02, -4.28323418e-01,
        -1.25632957e-02,  9.53804553e-02, -1.48064166e-01,
        -1.36022404e-01,  2.64659435e-01, -9.64171350e-01,
         2.24916756e-01,  2.08654240e-01, -9.54005539e-01,
         3.16910520e-02,  7.06257463e-01, -9.78959560e-01,
        -8.87598813e-01, -1.44877046e-01,  9.65375423e-01,
        -9.84477460e-01,  8.98248136e-01,  2.68709451e-01,
         2.23330960e-01,  8.40342522e-01,  1.81138456e-01,
        -9.42791700e-02, -6.14357088e-03, -9.93321121e-01,
        -2.18152031e-01,  8.68108273e-01,  5.73083520e-01,
         1.61648810e-01,  4.83666897e-01,  7.53923655e-02,
         3.11868161e-01,  2.62609422e-01,  3.09002429e-01,
        -1.98142633e-01, -4.29599397e-02,  4.05657679e-01,
        -1.85890302e-01, -1.03287257e-01, -2.04379812e-01,
        -9.35318232e-01, -3.87524992e-01, -1.39134333e-01,
        -6.95273459e-01, -2.93173403e-01,  7.65915811e-01,
         2.00152248e-01, -1.38822198e-01, -3.08986157e-02,
        -1.62600782e-02,  2.01037243e-01,  3.75104338e-01,
         5.05390227e-01, -2.16556609e-01,  2.07075194e-01,
         4.92450058e-01,  4.81427833e-02, -3.14956069e-01,
         9.83587742e-01,  9.60531592e-01, -1.21821143e-01,
         3.46079886e-01,  8.57113659e-01, -2.91336805e-01,
         3.04229349e-01, -2.11862415e-01,  2.86017716e-01,
         6.99932754e-01,  7.84478113e-02,  4.52353567e-01,
        -9.05753449e-02, -4.33456488e-02,  9.82931137e-01,
         1.54376328e-01, -9.49543834e-01, -5.49556732e-01,
        -4.07908350e-01,  3.51450831e-01,  6.07469857e-01,
         1.90898567e-01, -1.79890543e-01, -9.44009900e-01,
        -2.93836504e-01,  1.98671237e-01,  9.72781122e-01,
        -5.80249280e-02, -5.33373296e-01,  3.06703031e-01,
         9.69025612e-01,  8.83269906e-01,  8.78389835e-01,
        -1.69684634e-01,  1.06114551e-01,  3.69123071e-01,
        -7.36990348e-02,  1.98133394e-01,  9.73687589e-01,
         2.22880766e-01, -6.12512589e-01,  3.02608490e-01,
        -3.90808851e-01,  9.42796052e-01,  9.76703241e-02,
        -2.25646198e-01,  9.77382600e-01, -4.26871359e-01,
        -6.78009242e-02,  3.70425552e-01,  1.85763240e-01,
         5.76871872e-01,  5.22106051e-01, -8.37408662e-01,
        -2.10144073e-01, -9.03320611e-01, -5.37356362e-02,
         4.02004659e-01,  3.97008717e-01,  6.51714146e-01,
         2.66446173e-01, -2.42695972e-01, -4.49011654e-01,
        -8.62734258e-01,  2.07311079e-01,  9.48280454e-01,
        -8.51842403e-01, -4.51601267e-01,  1.05238803e-01,
         2.73797095e-01,  5.73096991e-01, -9.49941128e-02,
         2.02849776e-01,  3.25465091e-02, -2.32741132e-01,
        -6.30199194e-01, -8.83479774e-01,  1.96812406e-01,
        -9.83280420e-01,  4.99083340e-01, -6.69117987e-01,
        -1.81619912e-01,  4.78357762e-01,  1.34498015e-01,
         5.19081056e-01, -8.91454935e-01,  1.98307440e-01,
         2.48759657e-01, -1.20972842e-02, -7.16826797e-01,
         3.24472249e-01,  4.77240197e-02, -4.20286320e-02,
        -3.48206609e-01,  8.73432308e-02,  4.56932724e-01,
        -9.69818830e-01,  1.75582975e-01,  6.34772718e-01,
         2.82631725e-01, -3.00625056e-01, -3.68915945e-01,
         9.35623795e-02,  1.05510447e-02, -5.57214096e-02,
        -4.14164782e-01,  1.18878253e-01, -7.77781665e-01,
        -4.14886206e-01,  5.03882468e-01,  3.94151434e-02,
        -9.37656462e-02,  1.89158991e-01, -1.98139355e-01,
        -2.15176389e-01,  4.25511450e-01,  4.69621390e-01,
         3.34833741e-01,  2.55942523e-01,  9.59043622e-01,
        -2.16007233e-01,  9.95777845e-01, -6.05499923e-01,
        -9.68729317e-01, -9.87926602e-01,  2.46115178e-01,
         6.04116738e-01,  9.62429583e-01, -5.22974789e-01,
        -6.68663800e-01, -4.35171545e-01, -6.84998751e-01,
        -2.14838117e-01, -1.07124291e-01, -5.66511750e-01,
        -5.26742041e-01,  3.29348326e-01, -8.50784719e-01,
         1.56987563e-01, -1.17007047e-01,  4.71079618e-01,
        -4.97265279e-01,  3.07917863e-01, -4.70311075e-01,
         4.08556193e-01,  4.71035004e-01, -7.33443350e-02,
         3.54574829e-01,  1.61313154e-02, -3.38875324e-01,
         9.85911369e-01,  7.26910904e-02,  1.13832854e-01,
        -1.05385393e-01, -1.06901139e-01,  1.23381898e-01,
         9.55644071e-01, -5.51126063e-01, -9.94152069e-01,
         4.99909669e-01,  1.07629541e-02,  1.49309844e-01,
        -1.52286172e-01,  2.98955202e-01,  1.04692079e-01,
        -1.38500715e-02,  9.82759893e-01,  2.65631378e-01,
        -3.07423584e-02,  4.24245626e-01,  9.57974911e-01,
        -3.71754775e-03, -3.22169960e-01, -7.97318161e-01,
        -9.57811356e-01, -3.67215544e-01, -4.65155929e-01,
         9.39662695e-01,  2.64033973e-01,  8.48620236e-01,
        -5.66752888e-02, -6.25285745e-01,  1.22017063e-01,
         7.89123237e-01, -1.24257663e-02, -7.24532306e-01,
        -3.73808026e-01, -1.06144942e-01,  9.40802038e-01,
         3.53034854e-01,  8.80552948e-01,  8.75615716e-01,
        -4.98496294e-01,  4.25589859e-01,  2.83696987e-02,
         1.49165273e-01,  2.53175795e-01, -4.07062590e-01,
         2.98888147e-01,  7.52664149e-01, -4.24239367e-01,
        -9.77308869e-01, -4.32953149e-01,  4.31041002e-01,
        -1.19505003e-01,  1.69369906e-01,  3.15835536e-01,
        -7.87555516e-01, -5.74999824e-02, -1.56140164e-01,
        -8.46194506e-01, -1.64312005e-01, -7.56849527e-01,
        -9.57364082e-01,  6.36766791e-01, -5.92576623e-01,
         5.48811078e-01, -3.97690944e-02, -9.25925255e-01,
        -9.48922455e-01, -3.25103372e-01, -1.43624917e-01,
        -2.46628523e-01,  2.23922908e-01,  2.43986621e-01,
        -9.74319756e-01, -5.93192056e-02, -6.32839918e-01,
        -1.65967532e-02,  2.12513477e-01,  8.23914632e-02,
        -1.95247114e-01,  1.70667265e-02, -1.03817105e-01,
         9.67006028e-01,  8.94040585e-01,  6.45594239e-01,
        -8.24017525e-01,  4.99865443e-01,  2.62904372e-02,
        -6.08126640e-01,  1.33460507e-01,  7.32902527e-01,
         5.31469695e-02, -2.85471454e-02,  4.22591746e-01,
         8.13042164e-01, -2.11627424e-01, -7.92580992e-02,
        -4.31119233e-01,  1.07735276e-01,  9.54904929e-02,
        -3.15252751e-01,  7.17674851e-01,  7.27219954e-02,
         6.14280820e-01, -4.04972211e-02,  8.88640940e-01,
        -3.38066638e-01,  2.79680669e-01, -4.84734058e-01,
         2.40349486e-01, -6.41798452e-02, -1.83843866e-01,
        -1.57174185e-01, -1.81520194e-01, -9.47541356e-01,
        -2.55872849e-02, -7.41722047e-01,  9.22453046e-01,
        -4.74170476e-01, -2.39291772e-01,  6.00637235e-02,
        -3.85925204e-01, -2.55775243e-01, -6.41549647e-01,
        -5.38084328e-01,  9.24636662e-01, -7.97648489e-01,
         2.51554519e-01,  1.95232764e-01,  1.40810892e-01,
        -9.37027931e-01, -2.52226830e-01, -4.64764059e-01,
        -4.43974137e-01, -5.31123698e-01, -1.50237948e-01,
        -2.89001018e-02, -9.52682674e-01, -2.69514799e-01,
         2.78669953e-01,  1.17901191e-01,  3.02110106e-01,
         9.76273239e-01, -4.78814811e-01, -6.99187592e-02,
         1.69064462e-01, -8.07212770e-01, -8.74855369e-03,
         4.52212244e-01,  7.66888678e-01, -9.28449392e-01,
         4.01067808e-02,  4.73369926e-01, -5.06339550e-01,
        -9.89685178e-01,  4.99515086e-02,  1.61314934e-01,
         4.47093636e-01,  1.56272687e-02,  6.21569216e-01,
         1.45927936e-01, -5.72664797e-01, -5.15100837e-01,
         9.70511854e-01,  9.29408893e-02,  6.93095684e-01,
        -2.00693414e-01, -9.43685174e-01,  3.05221498e-01,
         5.77920258e-01, -8.38481545e-01,  8.48024249e-01,
         1.03882320e-01,  4.80521619e-01,  4.69195098e-01,
         2.22260565e-01, -5.00070632e-01, -8.10905814e-01,
         3.03559124e-01, -5.83350658e-01,  9.28008020e-01,
         3.67301077e-01, -7.80744553e-02, -2.28819028e-01,
        -3.18179876e-01, -9.29315567e-01,  8.43946099e-01,
         8.09551656e-01, -1.91499323e-01, -2.01791495e-01,
         4.22167510e-01, -7.80887246e-01, -2.45667964e-01,
         3.91157329e-01, -2.63040006e-01, -9.70705032e-01,
        -2.63322502e-01, -8.73468757e-01,  2.66760767e-01,
         3.61471474e-01, -5.06052673e-01, -2.21734866e-04,
        -9.49694216e-01,  2.99235493e-01,  9.75558221e-01,
         9.15814579e-01,  5.07332742e-01, -1.55603185e-01,
         2.72963375e-01, -9.97526586e-01, -9.75885093e-01,
         6.22023605e-02,  3.43675315e-01,  2.09447846e-01,
        -4.92990855e-03,  1.35019422e-01, -5.26014090e-01,
        -1.21381849e-01,  1.37544364e-01,  3.71199667e-01,
         1.59986675e-01, -8.27998519e-02,  2.10709181e-02,
        -9.58102822e-01,  4.46091026e-01, -3.70041311e-01,
         4.70448891e-03,  1.83326229e-01, -3.45449895e-01,
        -9.96411979e-01, -2.50673175e-01,  1.00153595e-01,
         4.89037544e-01, -8.54706019e-02,  1.32991463e-01,
        -3.53267416e-02,  3.05146217e-01, -8.19448009e-02,
         5.09760380e-01,  6.09930884e-03,  6.93550825e-01,
        -2.20735162e-01, -2.98067957e-01,  6.18630275e-02,
        -3.36927921e-01, -7.71910191e-01, -7.68832743e-01,
         1.02353990e-01, -3.36008877e-01, -6.62945330e-01,
         3.12878460e-01, -8.20462763e-01,  4.99513209e-01,
        -4.05179352e-01, -9.48880333e-03,  1.90918282e-01,
        -1.29997402e-01,  6.69021681e-02, -3.81052890e-03,
        -1.97349146e-01, -1.49638802e-01, -8.86062920e-01,
         9.75499392e-01, -8.71507466e-01, -8.82685661e-01,
        -7.30049431e-01, -7.23563554e-03, -9.83256876e-01,
         3.49731773e-01, -9.53792572e-01,  7.61278793e-02,
         6.96366131e-01,  5.24698615e-01, -1.62975825e-02,
         3.15798610e-01, -1.11974906e-02, -4.73921932e-02,
         2.78857108e-02,  2.69806564e-01, -3.41300100e-01,
         3.02773446e-01,  5.23383856e-01,  1.07574344e-01,
        -4.89515103e-02, -7.14161217e-01, -7.97810778e-02,
         3.83901745e-01, -4.06342596e-01, -4.09604609e-01,
         2.03187868e-01,  3.33308995e-01, -2.62467951e-01,
         4.49400783e-01, -6.77599132e-01, -1.65016249e-01,
         3.20492208e-01, -1.92335725e-01,  9.84863818e-01,
        -3.68369877e-01, -9.01189089e-01, -3.82667422e-01,
        -3.91704619e-01,  3.39026637e-02,  3.07124227e-01,
        -5.33119440e-01,  9.67842281e-01,  9.65332031e-01,
         6.80126995e-02, -8.49797502e-02,  8.92477274e-01,
         2.85910189e-01, -5.12139015e-02,  7.06737399e-01,
         1.55301109e-01,  8.73320162e-01,  2.09254935e-01,
        -2.41922587e-01, -9.71848607e-01,  3.79644811e-01,
         3.03405881e-01,  1.65485874e-01,  5.21821439e-01,
         2.98166692e-01, -9.94420350e-01,  6.23600483e-01,
         3.61348502e-02,  2.62313010e-03, -3.46994959e-02,
         5.31516552e-01,  6.41021311e-01,  1.53670430e-01,
         1.67008385e-01,  1.59718275e-01, -9.71159562e-02,
        -7.38702118e-01,  2.03659073e-01,  6.05829135e-02,
        -7.40107670e-02, -7.06449449e-02,  9.52102095e-02,
        -8.75447512e-01,  3.41838658e-01, -4.73477364e-01,
         1.28834650e-01,  9.00416374e-01,  3.52474242e-01,
         4.18331027e-01,  6.04468346e-01,  3.51824254e-01,
        -1.83769584e-01, -9.12266910e-01, -2.02515379e-01,
         5.74004464e-02, -3.64134371e-01, -5.13147265e-02,
        -3.61909807e-01,  6.31736442e-02,  7.70528316e-01,
         1.13558754e-01,  8.35388675e-02, -3.95380527e-01,
         1.21655585e-02,  8.94883037e-01,  7.09097922e-01,
         2.10421145e-01,  9.15897548e-01,  3.72566342e-01,
         3.18074226e-01, -5.20140052e-01, -2.94945329e-01,
        -5.56653738e-01, -5.44920564e-01, -5.58629394e-01,
        -3.18388313e-01,  1.96677864e-01,  3.92639309e-01,
        -5.57219610e-02,  9.43165898e-01, -2.46770516e-01,
        -5.63873127e-02, -9.74237978e-01, -7.33558953e-01,
        -4.73253161e-01, -4.56261821e-02, -3.31606805e-01,
         2.26265267e-01,  7.41893291e-01,  3.07435513e-01,
        -5.91276325e-02, -1.63760439e-01,  3.32902282e-01,
         4.76788580e-01,  1.73780680e-01, -6.09735966e-01,
         6.47488773e-01,  9.69663084e-01,  5.25310218e-01,
         7.37583280e-01, -2.31564134e-01,  9.30888593e-01,
         3.55679274e-01,  2.32671618e-01, -2.00382099e-01,
         4.90927786e-01,  5.97352326e-01,  2.90029138e-01,
        -2.82738209e-01,  1.76125839e-01,  1.35503132e-02,
         3.01990837e-01,  4.73168582e-01,  7.56138265e-02,
         2.11966351e-01, -3.19474846e-01,  9.30948615e-01,
        -1.63534340e-02,  6.44839644e-01, -1.08461894e-01,
        -5.49069285e-01, -3.51361781e-01, -2.18221009e-01,
        -6.01581097e-01,  6.96052909e-01,  3.21235389e-01,
         1.39229503e-02,  3.91206175e-01, -1.17417075e-01,
        -3.80528659e-01, -1.47984892e-01,  2.81231999e-01,
        -1.70889780e-01, -5.57830691e-01, -4.72577214e-01,
         2.16857657e-01, -4.95298728e-02,  1.23911379e-02,
         1.27670867e-02,  7.16542780e-01, -2.90986747e-02,
         9.01290029e-02, -3.81600201e-01, -3.91617656e-01,
         9.51459825e-01, -7.22808599e-01, -2.17146054e-01,
         2.35675052e-01,  9.85051751e-01, -2.02287197e-01,
        -1.46612599e-01, -4.97791499e-01, -7.73974419e-01,
        -4.95315254e-01, -2.29405120e-01, -1.94181781e-02,
         4.28553253e-01,  5.66722274e-01, -6.05644658e-02,
        -9.45692658e-02,  5.63955486e-01,  3.55487317e-01,
        -8.26581359e-01,  9.62330043e-01,  9.67989147e-01,
         3.79804313e-01, -6.03192210e-01,  3.98838729e-01,
         6.07165277e-01,  9.77703035e-01,  3.40008736e-01,
         5.90980530e-01, -9.17209506e-01,  9.71336722e-01,
        -1.83312625e-01,  1.03359088e-01, -2.17738375e-01,
        -2.04023987e-01,  1.61539331e-01, -9.02490795e-01,
         1.30582741e-02,  9.68311876e-02,  4.06291068e-01,
         7.19882131e-01, -3.87988716e-01,  3.24509740e-01,
         1.37943909e-01,  9.82864261e-01,  2.39320174e-02,
         4.74716514e-01, -4.16517287e-01,  2.25814700e-01]], dtype=float32), array([[ 7.22913072e-02,  2.51380019e-02,  9.59419906e-01,
        -3.53312373e-01,  1.67284861e-01, -1.26533151e-01,
        -1.76939443e-01, -5.76093197e-02,  8.78013194e-01,
        -3.53835940e-01,  9.28695619e-01,  2.25299776e-01,
         6.80881083e-01, -9.54788566e-01, -6.23067617e-01,
         4.07695323e-01,  2.66853034e-01, -2.91408539e-01,
        -4.27209496e-01,  1.29733816e-01,  2.41983578e-01,
        -4.90773231e-01,  8.11422765e-01,  7.48537295e-03,
         5.03362298e-01, -6.28607094e-01,  3.09202254e-01,
         7.74953365e-01,  1.66026041e-01, -7.75671065e-01,
         5.89130388e-04,  5.28821051e-01,  3.35004419e-01,
        -1.75983816e-01,  9.49709594e-01, -6.89838886e-01,
         4.67070967e-01, -8.57684538e-02,  1.30437046e-01,
        -1.82990193e-01, -2.16319472e-01,  6.27515018e-02,
        -6.72144830e-01, -9.36894417e-01,  6.86961487e-02,
        -2.33197123e-01,  9.86822069e-01,  3.45608056e-01,
         1.37899920e-01, -9.77217376e-01, -9.81504738e-01,
        -9.52705860e-01, -5.45755863e-01, -2.40264889e-02,
        -4.00248654e-02,  7.09665060e-01,  5.07703662e-01,
         4.75042641e-01, -2.33417496e-01, -1.90987475e-02,
        -2.28650063e-01,  4.67271805e-01,  6.16302907e-01,
        -5.64977705e-01, -9.98262465e-01, -9.83431160e-01,
         2.45825052e-01,  2.09649261e-02, -2.95940071e-01,
        -1.57183930e-01,  2.18817145e-01, -2.52806515e-01,
        -3.31348002e-01,  2.03940570e-01, -9.85036492e-01,
         2.78506935e-01,  2.07541093e-01, -9.76850688e-01,
         3.68352607e-03,  6.89378083e-01, -9.91967797e-01,
        -9.15037751e-01, -1.31595656e-01,  9.88247454e-01,
        -9.91374373e-01,  9.41127121e-01,  2.84675300e-01,
         1.68782502e-01,  8.36568594e-01,  1.41021922e-01,
         1.26048429e-02, -9.53763947e-02, -9.96956885e-01,
        -2.49096781e-01,  8.08413386e-01,  5.50096810e-01,
         5.86430989e-02,  7.06347823e-01,  4.27479781e-02,
         3.70504707e-01,  2.13215515e-01,  2.56207138e-01,
        -1.70544893e-01, -5.83989508e-02,  4.86411273e-01,
        -2.49841809e-01, -4.71380465e-02, -1.72956705e-01,
        -9.44868863e-01, -3.43881667e-01, -1.50859758e-01,
        -7.44823933e-01, -2.69862235e-01,  8.97326648e-01,
         2.69712687e-01, -2.23148242e-01,  3.25054340e-02,
         8.53514597e-02,  2.13333488e-01,  4.86670792e-01,
         3.98322374e-01, -7.58813554e-03,  3.50288391e-01,
         6.15259349e-01,  7.00105056e-02, -3.57212007e-01,
         9.93982852e-01,  9.80852246e-01, -2.42216378e-01,
         3.59699279e-01,  8.48942280e-01, -2.46763632e-01,
         3.82026821e-01, -2.30352908e-01,  2.06035733e-01,
         6.53126955e-01,  1.20569624e-01,  5.04781842e-01,
         7.66557362e-03, -5.78524023e-02,  9.92989421e-01,
        -3.20597291e-01, -9.74747121e-01, -6.19554043e-01,
        -4.70370770e-01,  4.77420807e-01,  5.40814877e-01,
         1.90747619e-01, -2.71517843e-01, -9.57288921e-01,
        -3.44147772e-01,  6.57487214e-02,  9.80615616e-01,
        -6.46412149e-02, -6.38503373e-01,  3.20677102e-01,
         9.74855840e-01,  9.23899949e-01,  8.96241426e-01,
        -2.05509782e-01,  3.99003662e-02,  5.21238744e-01,
        -1.54688060e-01,  2.68093348e-01,  9.79329586e-01,
         1.69456497e-01, -7.21556544e-01,  2.67214984e-01,
        -4.31561232e-01,  9.50549483e-01,  9.35011208e-02,
        -1.83131278e-01,  9.88702297e-01, -3.93060833e-01,
         1.15712479e-01,  5.25933921e-01,  4.26350832e-01,
         6.78287089e-01,  5.43742120e-01, -8.71685028e-01,
        -1.60270527e-01, -9.09132063e-01,  5.91616444e-02,
         4.65151429e-01,  4.97237235e-01,  7.17420578e-01,
         4.52188730e-01, -3.05546552e-01, -5.39495945e-01,
        -7.55943775e-01,  2.80580729e-01,  9.58473027e-01,
        -8.30063879e-01, -3.83056849e-01,  6.72947839e-02,
         2.85726517e-01,  7.89294481e-01, -9.26066190e-02,
         1.39832065e-01,  1.06499746e-01, -1.34877473e-01,
        -5.28599679e-01, -8.76997828e-01,  3.75690848e-01,
        -9.93042886e-01,  4.38971341e-01, -6.56328559e-01,
        -1.67096078e-01,  5.89445651e-01,  8.41251463e-02,
         4.90941584e-01, -8.86405468e-01,  2.17713162e-01,
         3.15968871e-01, -1.43981308e-01, -7.64533579e-01,
         3.45655680e-01, -3.17224264e-02, -1.27431646e-01,
        -4.35941428e-01,  5.99434301e-02,  5.61292291e-01,
        -9.87608850e-01,  2.33035639e-01,  6.55350327e-01,
         2.16307580e-01, -2.92762458e-01, -4.28077698e-01,
        -2.45598219e-02, -1.82968006e-02, -1.83389828e-01,
        -6.01343989e-01,  9.89272967e-02, -7.82457054e-01,
        -5.02480805e-01,  7.26176918e-01,  1.47319227e-01,
        -4.85645421e-03,  1.44722268e-01, -2.41576195e-01,
        -2.28415146e-01,  5.60698569e-01,  4.95221525e-01,
         3.58632147e-01,  2.39187434e-01,  9.78928566e-01,

In [ ]:
model.save("bert_model_corpus")

In [ ]:
sen2 = query_array_processed
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')
#Encoding:
sen_embeddings2 = model.encode(sen2)
sen_embeddings2.shape

(50, 768)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
#let's calculate cosine similarity for sentence 0:
cosine_similarity(
    [sen_embeddings2[0]],
    sen_embeddings
)

array([[0.6412729 , 0.62807184, 0.624091  , ..., 0.5693726 , 0.6384668 ,
        0.54456216]], dtype=float32)

In [ ]:
sl2=np.argsort(sl[0])
sl2=sl2[::-1]

In [ ]:
z=[]
for j in range(10):
    z.append(df_filename.iloc[sl2[j]]['Name'].split('.')[0])
print(z)

['C1405', 'C1843', 'C829', 'C1088', 'C630', 'C647', 'C788', 'C306', 'C1969', 'C2876']

In [ ]:
count = 0
for i in range(50):
    sl=cosine_similarity([sen_embeddings2[i]],sen_embeddings)
    sl2=np.argsort(sl[0])[::-1]
    z=[]
    for q in range(20):
        z.append(df_filename.iloc[sl2[q]]['Name'].split('.')[0])
            
    for j in z:
        for k in evaluate.loc[evaluate['Query_Number'] == "AILA_Q"+str(i+1)]["Document"]:
            if (j==k):
                count=count+1
    print(z,count)            

print(count)

['C1405', 'C1843', 'C829', 'C1088', 'C630', 'C647', 'C788', 'C306', 'C1969', 'C2876', 'C1523', 'C2611', 'C1952', 'C347', 'C2119', 'C2834', 'C39', 'C660', 'C628', 'C1663'] 0
['C1357', 'C626', 'C117', 'C194', 'C1620', 'C444', 'C1440', 'C1589', 'C1468', 'C2576', 'C956', 'C192', 'C449', 'C1971', 'C2340', 'C713', 'C50', 'C1828', 'C522', 'C398'] 0
['C294', 'C2533', 'C2711', 'C2241', 'C2842', 'C2111', 'C439', 'C679', 'C56', 'C639', 'C2576', 'C1945', 'C2321', 'C288', 'C1589', 'C2302', 'C2508', 'C8', 'C579', 'C92'] 0
['C600', 'C1037', 'C233', 'C645', 'C654', 'C1728', 'C1709', 'C2791', 'C1103', 'C487', 'C1254', 'C2270', 'C1286', 'C1689', 'C2744', 'C1515', 'C1431', 'C650', 'C1591', 'C1110'] 0
['C144', 'C566', 'C681', 'C315', 'C875', 'C2229', 'C2100', 'C1844', 'C2125', 'C615', 'C1813', 'C1646', 'C471', 'C2573', 'C2291', 'C2408', 'C2355', 'C39', 'C2309', 'C1817'] 1
['C2316', 'C997', 'C184', 'C2245', 'C397', 'C2914', 'C1339', 'C51', 'C2419', 'C1305', 'C2904', 'C1687', 'C2454', 'C37', 'C1709', 'C549', 'C2690', 'C2727', 'C2142', 'C2074'] 1
['C501', 'C2822', 'C1831', 'C963', 'C1440', 'C343', 'C117', 'C1633', 'C240', 'C2641', 'C1063', 'C1676', 'C2219', 'C787', 'C2332', 'C1620', 'C19', 'C2651', 'C150', 'C679'] 1
['C1728', 'C2607', 'C365', 'C600', 'C991', 'C2406', 'C1689', 'C1037', 'C1329', 'C1817', 'C2270', 'C650', 'C1431', 'C1942', 'C487', 'C1760', 'C1709', 'C1103', 'C848', 'C2791'] 1
['C1949', 'C875', 'C2035', 'C566', 'C397', 'C2054', 'C1591', 'C1339', 'C1987', 'C315', 'C2291', 'C1352', 'C1963', 'C1440', 'C1539', 'C1286', 'C2420', 'C1063', 'C78', 'C117'] 1
['C990', 'C122', 'C2526', 'C2664', 'C1083', 'C2682', 'C2641', 'C1836', 'C2222', 'C59', 'C1522', 'C2055', 'C1249', 'C1816', 'C592', 'C1814', 'C693', 'C1652', 'C1079', 'C1385'] 1
['C2083', 'C875', 'C243', 'C2876', 'C204', 'C679', 'C43', 'C194', 'C1873', 'C7', 'C1646', 'C140', 'C2125', 'C1844', 'C388', 'C2241', 'C2138', 'C1843', 'C639', 'C1173'] 1
['C1591', 'C376', 'C1963', 'C78', 'C1063', 'C117', 'C1286', 'C487', 'C2400', 'C768', 'C658', 'C1709', 'C2607', 'C397', 'C2102', 'C19', 'C2822', 'C240', 'C554', 'C1760'] 1
['C1592', 'C875', 'C34', 'C1684', 'C842', 'C918', 'C2125', 'C549', 'C194', 'C1287', 'C2321', 'C204', 'C514', 'C817', 'C1260', 'C349', 'C1463', 'C1725', 'C2541', 'C2054'] 1
['C1620', 'C1063', 'C2822', 'C962', 'C2035', 'C1339', 'C1957', 'C1440', 'C1928', 'C2437', 'C1707', 'C664', 'C1626', 'C1352', 'C787', 'C200', 'C2304', 'C2293', 'C1425', 'C990'] 1
['C2766', 'C2751', 'C297', 'C2823', 'C2005', 'C205', 'C376', 'C185', 'C2417', 'C2715', 'C1934', 'C122', 'C2896', 'C1063', 'C2025', 'C1305', 'C19', 'C1816', 'C2260', 'C397'] 2
['C664', 'C2301', 'C1063', 'C2487', 'C2482', 'C2205', 'C1247', 'C2839', 'C2715', 'C1492', 'C688', 'C1016', 'C669', 'C440', 'C559', 'C960', 'C1496', 'C2435', 'C185', 'C437'] 2
['C1845', 'C150', 'C499', 'C1873', 'C1725', 'C1731', 'C1015', 'C8', 'C2413', 'C2138', 'C2332', 'C1260', 'C304', 'C2533', 'C390', 'C215', 'C1421', 'C935', 'C2542', 'C343'] 2
['C365', 'C219', 'C639', 'C975', 'C117', 'C398', 'C2648', 'C344', 'C2744', 'C626', 'C2844', 'C1433', 'C2791', 'C2332', 'C1440', 'C2138', 'C194', 'C1589', 'C141', 'C2384'] 2
['C2558', 'C751', 'C580', 'C664', 'C2222', 'C358', 'C1464', 'C168', 'C440', 'C2025', 'C1620', 'C592', 'C2035', 'C1063', 'C2890', 'C1978', 'C1492', 'C1529', 'C2671', 'C185'] 2
['C2467', 'C1630', 'C1496', 'C1016', 'C1171', 'C1968', 'C2053', 'C559', 'C348', 'C618', 'C794', 'C130', 'C2007', 'C402', 'C2301', 'C2148', 'C2487', 'C1247', 'C644', 'C2132'] 2
['C681', 'C1954', 'C1013', 'C615', 'C1718', 'C543', 'C1985', 'C733', 'C1058', 'C931', 'C218', 'C1877', 'C1125', 'C1813', 'C691', 'C1399', 'C1122', 'C503', 'C1014', 'C461'] 2
['C644', 'C100', 'C794', 'C402', 'C348', 'C2148', 'C2774', 'C1496', 'C269', 'C2007', 'C2816', 'C1016', 'C1462', 'C215', 'C1996', 'C2725', 'C2132', 'C2101', 'C1630', 'C2099'] 2
['C2119', 'C111', 'C681', 'C388', 'C1287', 'C2466', 'C1844', 'C450', 'C733', 'C311', 'C252', 'C2876', 'C645', 'C875', 'C2495', 'C2516', 'C400', 'C291', 'C2681', 'C218'] 2
['C2404', 'C365', 'C2205', 'C344', 'C398', 'C1622', 'C2291', 'C626', 'C1620', 'C1739', 'C2137', 'C935', 'C2357', 'C1357', 'C1957', 'C1440', 'C1485', 'C1063', 'C2437', 'C2545'] 2
['C48', 'C1199', 'C1187', 'C2442', 'C1835', 'C2026', 'C2076', 'C1080', 'C1022', 'C2697', 'C1330', 'C927', 'C1455', 'C945', 'C1980', 'C1477', 'C1244', 'C1222', 'C756', 'C41'] 3
['C889', 'C1639', 'C1416', 'C82', 'C114', 'C2220', 'C141', 'C1357', 'C248', 'C1397', 'C173', 'C11', 'C194', 'C964', 'C2144', 'C1877', 'C1421', 'C1447', 'C308', 'C349'] 3
['C91', 'C571', 'C2474', 'C679', 'C2570', 'C420', 'C1421', 'C2452', 'C2360', 'C963', 'C1551', 'C639', 'C2534', 'C519', 'C2160', 'C1231', 'C2418', 'C2147', 'C366', 'C92'] 4
['C402', 'C2007', 'C2487', 'C2839', 'C559', 'C2671', 'C2768', 'C1247', 'C2437', 'C479', 'C444', 'C1016', 'C2542', 'C2059', 'C2347', 'C816', 'C1492', 'C1256', 'C1620', 'C1260'] 4
['C1709', 'C2607', 'C2400', 'C1286', 'C768', 'C1591', 'C2274', 'C376', 'C554', 'C2330', 'C487', 'C2102', 'C1063', 'C78', 'C1460', 'C117', 'C1963', 'C498', 'C693', 'C2326'] 4
['C1286', 'C768', 'C1037', 'C1709', 'C117', 'C78', 'C2791', 'C1591', 'C1515', 'C2400', 'C658', 'C376', 'C2860', 'C1728', 'C1963', 'C2102', 'C673', 'C1063', 'C452', 'C1431'] 4
['C2576', 'C706', 'C313', 'C1321', 'C56', 'C439', 'C1197', 'C1357', 'C685', 'C1589', 'C1480', 'C2179', 'C463', 'C1917', 'C1181', 'C2288', 'C956', 'C2591', 'C1359', 'C494'] 4
['C1286', 'C1037', 'C117', 'C1709', 'C2860', 'C768', 'C2791', 'C2744', 'C78', 'C1135', 'C875', 'C1515', 'C487', 'C299', 'C365', 'C2607', 'C1063', 'C2102', 'C2400', 'C1591'] 4
['C794', 'C2768', 'C228', 'C2829', 'C1968', 'C773', 'C2301', 'C1247', 'C559', 'C348', 'C233', 'C2816', 'C1253', 'C1481', 'C2347', 'C820', 'C796', 'C2715', 'C1041', 'C381'] 4
['C1634', 'C1861', 'C2612', 'C420', 'C81', 'C572', 'C1730', 'C319', 'C1870', 'C2641', 'C611', 'C2849', 'C1282', 'C963', 'C1484', 'C151', 'C721', 'C537', 'C975', 'C2379'] 4
['C875', 'C117', 'C1987', 'C315', 'C78', 'C2849', 'C2744', 'C74', 'C2291', 'C2904', 'C1646', 'C1286', 'C566', 'C2408', 'C1110', 'C1460', 'C1709', 'C1949', 'C2495', 'C1873'] 4
['C2316', 'C1946', 'C2111', 'C37', 'C184', 'C17', 'C2527', 'C2469', 'C2914', 'C1581', 'C1924', 'C2166', 'C997', 'C1211', 'C2582', 'C870', 'C1736', 'C1982', 'C2834', 'C57'] 6
['C2301', 'C2482', 'C669', 'C1811', 'C2832', 'C794', 'C2774', 'C1804', 'C791', 'C1247', 'C2467', 'C960', 'C130', 'C2715', 'C1496', 'C365', 'C348', 'C747', 'C53', 'C644'] 6
['C679', 'C2004', 'C639', 'C2138', 'C2800', 'C420', 'C204', 'C2534', 'C889', 'C1582', 'C750', 'C343', 'C2834', 'C60', 'C135', 'C213', 'C963', 'C1747', 'C2166', 'C1867'] 6
['C2301', 'C348', 'C1496', 'C130', 'C1247', 'C2124', 'C100', 'C669', 'C618', 'C2768', 'C1804', 'C269', 'C773', 'C233', 'C1355', 'C644', 'C2148', 'C381', 'C2839', 'C794'] 6
['C287', 'C1078', 'C2165', 'C464', 'C904', 'C2708', 'C362', 'C1125', 'C439', 'C1945', 'C1981', 'C1097', 'C2624', 'C2644', 'C1101', 'C288', 'C1076', 'C174', 'C386', 'C1845'] 6
['C1063', 'C1591', 'C1286', 'C1963', 'C117', 'C2822', 'C487', 'C498', 'C768', 'C2205', 'C2137', 'C477', 'C1440', 'C688', 'C2326', 'C240', 'C2400', 'C1760', 'C962', 'C2307'] 6
['C1237', 'C287', 'C1421', 'C451', 'C1759', 'C1240', 'C400', 'C2842', 'C3', 'C532', 'C1362', 'C436', 'C388', 'C1433', 'C1389', 'C2533', 'C2321', 'C1411', 'C2442', 'C1961'] 6
['C2791', 'C2744', 'C1709', 'C117', 'C645', 'C1037', 'C1942', 'C650', 'C1110', 'C1515', 'C1254', 'C2406', 'C365', 'C344', 'C1677', 'C299', 'C2607', 'C1381', 'C1431', 'C2205'] 6
['C315', 'C2442', 'C1110', 'C963', 'C2573', 'C1677', 'C2863', 'C1440', 'C2291', 'C2637', 'C2058', 'C2418', 'C2712', 'C2332', 'C1555', 'C1135', 'C2466', 'C875', 'C2408', 'C699'] 6
['C875', 'C1844', 'C566', 'C1963', 'C1591', 'C240', 'C397', 'C600', 'C78', 'C1155', 'C1182', 'C1536', 'C1949', 'C2138', 'C1260', 'C1440', 'C1037', 'C1608', 'C2125', 'C816'] 7
['C642', 'C1462', 'C2797', 'C619', 'C1041', 'C1015', 'C206', 'C773', 'C1548', 'C2768', 'C949', 'C2711', 'C2476', 'C2671', 'C280', 'C596', 'C1956', 'C812', 'C2139', 'C2007'] 7
['C269', 'C348', 'C2007', 'C1496', 'C2301', 'C402', 'C2234', 'C1956', 'C2839', 'C233', 'C2768', 'C381', 'C618', 'C2148', 'C1462', 'C861', 'C773', 'C2124', 'C100', 'C1247'] 7
['C117', 'C572', 'C501', 'C963', 'C2641', 'C240', 'C1861', 'C1831', 'C343', 'C150', 'C1633', 'C2219', 'C2332', 'C2822', 'C1971', 'C1440', 'C2682', 'C787', 'C151', 'C2440'] 7
['C1858', 'C1260', 'C2332', 'C117', 'C2682', 'C1768', 'C240', 'C2641', 'C122', 'C1214', 'C1440', 'C2054', 'C2648', 'C787', 'C397', 'C1083', 'C2532', 'C1159', 'C1633', 'C1749'] 7
['C2071', 'C50', 'C2576', 'C2110', 'C976', 'C150', 'C264', 'C958', 'C1828', 'C1589', 'C888', 'C894', 'C449', 'C2671', 'C1533', 'C444', 'C2319', 'C2597', 'C2479', 'C736'] 7
7